<?php

namespace Vm\VmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository
{
	public function getKnowledgeComments($id)
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$qb->select(array('c','k','r'))
		->from('VmVmBundle:Comments','c')
		->leftJoin('c.knowledges','k')
		->leftJoin('c.commenter', 'r')
		->where ('k.id = :id')
		->setParameter('id', $id)
		->andWhere('c.is_activated = :is')
		->setParameter('is',1)
		->andWhere('c.commenter != :n')
		->setParameter('n','')
		->andWhere('r.is_approved = :ip')
		->setParameter('ip', 1)
		->orderBy('c.created_at','ASC');
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
