<?php

namespace Vm\VmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommenterRepository extends EntityRepository
{
	public function getLastCommenter()
	{
		$qb = $this->createQueryBuilder('c')
		->setMaxResults(1)
		->orderBy('c.created_at','DESC');
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
