security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
 
        secured_area:
            pattern:    ^/
            anonymous: ~
            logout:
                path:   /logout
                target: /
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: vm_vm_homepage
 
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
 
    providers:
        main:
            entity: { class: Vm\VmBundle\Entity\User, property: username }
 
    encoders:
        Vm\VmBundle\Entity\User: sha512
