vm-category:
    path:     /
    defaults: { _controller: "VmVmBundle:Category:index" }

vm-category_show:
    path:     /category/{slug}/{page}
    defaults: { _controller: "VmVmBundle:Category:show", page: 1 }

vm-category_new:
    path:     /new
    defaults: { _controller: "VmVmBundle:Category:new" }

vm-category_create:
    path:     /create
    defaults: { _controller: "VmVmBundle:Category:create" }
    requirements: { _method: post }

vm-category_edit:
    path:     /{id}/edit
    defaults: { _controller: "VmVmBundle:Category:edit" }

vm-category_update:
    path:     /{id}/update
    defaults: { _controller: "VmVmBundle:Category:update" }
    requirements: { _method: post|put }

vm-category_delete:
    path:     /{id}/delete
    defaults: { _controller: "VmVmBundle:Category:delete" }
    requirements: { _method: post|delete }
