Vm\VmBundle\Entity\Category:
 type: entity
 repositoryClass: Vm\VmBundle\Repository\CategoryRepository
 table: category
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
   length: 255
   unique: true
  slug:
   type: string
   length: 255
   unique: true
 oneToMany:
  knowledges:
   targetEntity: Knowledge
   mappedBy: category
 manyToMany:
  affiliates:
   targetEntity: Affiliate
   mappedBy: categories
 lifecycleCallbacks:
  prePersist: [ setSlugValue ]
  preUpdate: [ setSlugValue ]
  
   
